SET DEFINE OFF;
Insert into WM_FTP_CONNECTIONS
   (FTP_CONN_ID, FTP_SERVERHOST, FTP_SERVERPORT, FTP_USERNAME, FTP_PASSWORD, 
    FTP_BASE_DIR, DESCRIPTION, PROTOCOL, ACTIVE, CREATED_BY, 
    CREATED_DATE)
 Values
   ('PR78_MX_V2', '10.188.48.15', 22, 'posuser', 'posuser', 
    '/u01/posuser/FEMSA_OXXO/POS/', 'Buzón POS Desarrollo SFTP', 'SFTP', 'Y', 'WMUSER', 
    TO_TIMESTAMP('9/23/2026 1:56:01.369711 PM','fmMMfm/fmDDfm/YYYY fmHH12fm:MI:SS.FF AM'));
COMMIT;
